import React,{useMemo,useState}from'react';import{createRoot}from'react-dom/client';import{Music2,Coins,Trophy,Volume2,Zap}from'lucide-react';import'./style.css';
const sound={A:'ă',B:'b',C:'k',D:'d',E:'ĕ',F:'f',G:'g',H:'h',I:'ĭ',J:'j',K:'k',L:'l',M:'m',N:'n',O:'ŏ',P:'p',Q:'kw',R:'r',S:'s',T:'t',U:'ŭ',V:'v',W:'w',X:'ks',Y:'y',Z:'z'};
function App(){const[stage,setStage]=useState('intro'),[first,setFirst]=useState(''),[last,setLast]=useState(''),[coins,setCoins]=useState(0),[matches,setMatches]=useState([]),[pick,setPick]=useState(null);
const letters=useMemo(()=>[...new Set((first+last).toUpperCase().replace(/[^A-Z]/g,''))], [first,last]);
const cards=useMemo(()=>letters.flatMap((L,i)=>[{id:L+'U',key:L,type:'CAP',text:L},{id:L+'l',key:L,type:'LOW',text:L.toLowerCase()},{id:L+'s',key:L,type:'SOUND',text:'/'+sound[L]+'/'}]).sort(()=>.5-Math.random()),[stage]);
const tap=c=>{if(matches.includes(c.id))return;if(!pick){setPick(c);return}if(pick.key===c.key&&pick.type!==c.type){setMatches(m=>[...m,pick.id,c.id]);setCoins(x=>x+5);setPick(null)}else setPick(c)};
const complete=letters.length>0&&cards.every(c=>matches.includes(c.id));
if(stage==='intro')return <main><header><Music2/><b>READARAP</b><span>MAKE IT MAKE SENSE</span></header><section className="hero"><div className="tag">LEVEL 01 • NAME FLO</div><h1>YOUR NAME<br/>IS YOUR <em>FIRST BEAT.</em></h1><p>Start with what you already know. Your name.</p><div className="names"><input placeholder="First name" value={first} onChange={e=>setFirst(e.target.value)}/><input placeholder="Last name" value={last} onChange={e=>setLast(e.target.value)}/></div><button disabled={!first||!last} onClick={()=>setStage('drop')}><Zap/> ENTER NAME FLO</button></section></main>;
if(stage==='drop')return <main className="drop"><div className="bass"><Volume2/><small>BEATLORD SAYS</small><h1>DROP<br/>THE BASS.</h1><p>Your letters are about to get BUSSED DOWN.</p><button onClick={()=>setStage('match')}>💥 SCATTER MY NAME</button></div></main>;
return <main><header><Music2/><b>NAME FLO</b><div className="coin"><Coins/> {coins}</div></header><section className="game"><div className="progress"><span>REBUILD: {first.toUpperCase()} {last.toUpperCase()}</span><strong>{matches.length}/{cards.length}</strong></div><h2>MATCH YOUR LETTERS</h2><p>Match each CAPITAL + lowercase + sound.</p><div className="cards">{cards.map(c=><button key={c.id} className={'card '+(matches.includes(c.id)?'done':'')+(pick?.id===c.id?' picked':'')} onClick={()=>tap(c)}><small>{c.type==='CAP'?'LETTER NAME':c.type==='LOW'?'lowercase':'SOUND'}</small><b>{c.text}</b></button>)}</div>{complete&&<div className="win"><Trophy/><h2>NAME FLO COMPLETE!</h2><p>You rebuilt your name. Next stop: Alphabet Buss Down.</p><button onClick={()=>alert('Alphabet Buss Down unlocks next!')}>UNLOCK ALPHABET BUSS DOWN →</button></div>}</section></main>}
createRoot(document.getElementById('root')).render(<App/>);