import React,{useMemo,useState}from'react';import{createRoot}from'react-dom/client';import{Music2,Coins,Trophy,Volume2,Zap,Lock,CalendarDays}from'lucide-react';import'./style.css';
const sound={A:'ă',B:'b',C:'k',D:'d',E:'ĕ',F:'f',G:'g',H:'h',I:'ĭ',J:'j',K:'k',L:'l',M:'m',N:'n',O:'ŏ',P:'p',Q:'kw',R:'r',S:'s',T:'t',U:'ŭ',V:'v',W:'w',X:'ks',Y:'y',Z:'z'};
const alphabet='ABCDEFGHIJKLMNOPQRSTUVWXYZ'.split('');
const january={3:['jab','jam','jar','jaw','jay','jet','jig','job','jog','joy','jug'],4:['jazz','jeep','jerk','join','joke','jump','jury'],5:['jelly','joint','judge','juice','jumpy'],6:['jacket','jaguar','jingle','jovial','jungle'],7:['jackpot','jasmine','journey','justice'],8:['jubilant','junction','juvenile'],9:['jellyfish','judgment'],10:['journalists'],11:['journalistic'],12:['jurisdiction']};
function Header({title,coins}){return <header><Music2/><b>{title}</b><span>MAKE IT MAKE SENSE</span><div className="coin"><Coins/> {coins}</div></header>}
function App(){const[stage,setStage]=useState('intro'),[first,setFirst]=useState(''),[last,setLast]=useState(''),[coins,setCoins]=useState(0),[matches,setMatches]=useState([]),[pick,setPick]=useState(null),[grade,setGrade]=useState(3),[mastered,setMastered]=useState([]);
const letters=useMemo(()=>[...new Set((first+last).toUpperCase().replace(/[^A-Z]/g,''))],[first,last]);
const cards=useMemo(()=>letters.flatMap(L=>[{id:L+'U',key:L,type:'CAP',text:L},{id:L+'l',key:L,type:'LOW',text:L.toLowerCase()},{id:L+'s',key:L,type:'SOUND',text:'/'+sound[L]+'/'}]).sort(()=>.5-Math.random()),[stage]);
const tap=c=>{if(matches.includes(c.id))return;if(!pick){setPick(c);return}if(pick.key===c.key&&pick.type!==c.type){setMatches(m=>[...new Set([...m,pick.id,c.id])]);setCoins(x=>x+5);setPick(null)}else setPick(c)};
const complete=letters.length>0&&cards.every(c=>matches.includes(c.id));
const wordBank=january[grade]||[];
const master=w=>{if(!mastered.includes(w)){setMastered(m=>[...m,w]);setCoins(c=>c+10)}};
if(stage==='intro')return <main><Header title="READARAP" coins={coins}/><section className="hero"><div className="tag">LEVEL 01 • NAME FLO</div><h1>YOUR NAME<br/>IS YOUR <em>FIRST BEAT.</em></h1><p>Start with what you already know. Your name.</p><div className="names"><input placeholder="First name" value={first} onChange={e=>setFirst(e.target.value)}/><input placeholder="Last name" value={last} onChange={e=>setLast(e.target.value)}/></div><button disabled={!first||!last} onClick={()=>setStage('drop')}><Zap/> ENTER NAME FLO</button></section></main>;
if(stage==='drop')return <main className="drop"><div className="bass"><Volume2/><small>BEATLORD SAYS</small><h1>DROP<br/>THE BASS.</h1><p>Your letters are about to get BUSSED DOWN.</p><button onClick={()=>setStage('match')}>💥 SCATTER MY NAME</button></div></main>;
if(stage==='match')return <main><Header title="NAME FLO" coins={coins}/><section className="game"><div className="progress"><span>REBUILD: {first.toUpperCase()} {last.toUpperCase()}</span><strong>{matches.length}/{cards.length}</strong></div><h2>MATCH YOUR LETTERS</h2><p>Match each CAPITAL + lowercase + sound.</p><div className="cards">{cards.map(c=><button key={c.id} className={'card '+(matches.includes(c.id)?'done':'')+(pick?.id===c.id?' picked':'')} onClick={()=>tap(c)}><small>{c.type==='CAP'?'LETTER NAME':c.type==='LOW'?'lowercase':'SOUND'}</small><b>{c.text}</b></button>)}</div>{complete&&<div className="win"><Trophy/><h2>NAME FLO COMPLETE!</h2><p>You rebuilt your name. Alphabet Buss Down is unlocked.</p><button onClick={()=>setStage('alphabet')}>UNLOCK ALPHABET BUSS DOWN →</button></div>}</section></main>;
if(stage==='alphabet')return <main><Header title="ALPHABET BUSS DOWN" coins={coins}/><section className="game"><div className="tag">LEVEL 02 • WORD POWER</div><h2>BUSS DOWN A–Z</h2><p>Your name introduced the letters. Now build word power. January opens <b>J / “juh.”</b></p><div className="az">{alphabet.map(L=><button key={L} className={'azkey '+(L==='J'?'open':'')} disabled={L!=='J'} onClick={()=>L==='J'&&setStage('january')}>{L!=='J'&&<Lock/>}<b>{L}</b>{L==='J'&&<small>JAN</small>}</button>)}</div><div className="win"><CalendarDays/><h2>JANUARY IS OPEN</h2><p>Choose J to enter the grade × word-length ladder.</p></div></section></main>;
return <main><Header title="JANUARY • J / juh" coins={coins}/><section className="game"><button className="back" onClick={()=>setStage('alphabet')}>← A–Z BOARD</button><div className="gradebar"><div><small>CHOOSE GRADE</small><strong>GRADE {grade}</strong></div><input aria-label="grade" type="range" min="1" max="12" value={grade} onChange={e=>{setGrade(+e.target.value);setMastered([])}}/></div><h2>J WORD LADDER</h2><p>Grade {grade} = <b>{grade}-letter J words.</b> Learn it. Say it. Write it. Use it. Flow it.</p>{wordBank.length?<div className="words">{wordBank.map(w=><button key={w} className={mastered.includes(w)?'mastered':''} onClick={()=>master(w)}><small>{w.length} LETTERS</small><b>{w}</b><span>{mastered.includes(w)?'MASTERED ✓':'+10 RAPCOINS'}</span></button>)}</div>:<div className="empty"><h3>NO STANDARD {grade}-LETTER J WORD SET YET</h3><p>We don't invent words to fill a grade.</p></div>}<div className="progress"><span>J MASTERY</span><strong>{mastered.length}/{wordBank.length}</strong></div>{wordBank.length>0&&mastered.length===wordBank.length&&<div className="win"><Trophy/><h2>J BUSSED DOWN!</h2><p>Next progression: use your word power in the Lyric Swap Battle Room.</p><button onClick={()=>alert('Battle Room: Baby 50% → Lil 75% → Big 100%')}>ENTER BATTLE ROOM →</button></div>}</section></main>}
createRoot(document.getElementById('root')).render(<App/>);